### ISSUE TITLE
Crash on unexpected output

### ISSUE THREAD

**Issue by lezsakdomi** [althonos/ffpb#2]
Simply the script log:
```
 led@ledomi-pc  ~/Downloads/Louise L. Hay megerősítések/input   home ●  for f in c/*.mp4; do mkdir -p ../vcd/"`dirname "$f"`"; ffpb -i "$f" -target pal-vcd ../vcd/"$f".mpg; done 
c/A titok c. film  2006, eredeti magyar szinkron [360p].mp4 | ╢███████████████████████████████████████████████████████████████████╟ 100% (0:05:47 / 0:05:47)
c/A titok c. film  2006, eredeti magyar szinkron [360p].mp4 — ╢████████████████████████████████████████████████████████████████████╟ 100% (0:05:47 / 0:05:47
Exception in thread STDOUT/ERR thread for pid 7142:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/led/.local/lib64/python3.5/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/led/.local/lib64/python3.5/site-packages/sh.py", line 2484, in output_thread
    done = f.read()
  File "/home/led/.local/lib64/python3.5/site-packages/sh.py", line 2943, in read
    self.write_chunk(chunk)
  File "/home/led/.local/lib64/python3.5/site-packages/sh.py", line 2918, in write_chunk
    self.should_quit = self.process_chunk(chunk)
  File "/home/led/.local/lib64/python3.5/site-packages/sh.py", line 2839, in process
    return handler(chunk)
  File "/home/led/.local/lib64/python3.5/site-packages/sh.py", line 1624, in fn
    return handler(chunk, *args)
  File "/home/led/.local/lib64/python3.5/site-packages/ffpb.py", line 94, in __call__
    if char not in '\r\n':
TypeError: 'in <string>' requires string as left operand, not bytes


```

At this point ffmpeg runs in background, but the only thing on the console I can see is this error message, not the process.
I recommend as a hotfix catching errors at top level, and putting `ffmpeg` to the controlling terminal instead.

**Comment by lezsakdomi** [comment]
Please edit the title, most propably I am wrong.

**Comment by althonos** [comment]
This should not occur anymore :wink:
